### ISSUE TITLE
$pull not working

### ISSUE THREAD

**Issue by sakilo1990** [e-oj/Fawn#33] opened 2017-11-17 12:42 UTC
I have the following document:

`{
    "_id" : ObjectId("5846ac7b11f83798104e1fce"),
    "name" : "Yves",
    "surname" : "Rivard",
    "pending" : [ 
        {
            "seen" : false,
            "contract_id" : ObjectId("5a0ed25fbf3cd52f8413c4bf"),
            "signee_id" : ObjectId("5a0ed268bf3cd52f8413c4c0")
        }
    ]
}`

and I am trying to do the following update:

`task.update('users', { _id: mongoose.Types.ObjectId(req.user_id) }, { $pull: { pending: { contract_id: mongoose.Types.ObjectId(req.params.contract_id) } } })`

The object within the array does not get pulled out though. This same query works with mongoose:

`mongoose.model('users').update({ _id: mongoose.Types.ObjectId(req.user_id) }, { $pull: { pending: { contract_id: mongoose.Types.ObjectId(req.params.contract_id) } } }, function (err, result)
{}
)`

Any help would be appreciated.

**Comment by e-oj** [comment] 2017-11-17 13:36
Is there an error or does it just fail silently?

**Comment by sakilo1990** [comment] 2017-11-17 13:38
Just returns with nModified = 0

**Comment by e-oj** [comment] 2017-11-17 14:17
Alright. I'll try to reproduce it

**Comment by e-oj** [comment] 2017-11-17 14:19
In the mean time try the update without casting the id to ObjectId

**Comment by sakilo1990** [comment] 2017-11-17 14:21
Just tried and the result seems to be the same. If I replace the {$pull...} object with something like {$inc: {__v: 1}} then the update works so it is finding the overall document.

**Comment by e-oj** [comment] 2017-11-17 15:36
I haven't been able to reproduce this. It works for me. Note that if you run the same query twice, it'll fail if the first run already pulled the document. Here's the code I tried to reproduce with. Let me know if there are any significant differences.

```javascript
let task = Fawn.Task();

let Schema = new mongoose.Schema({
  name: String
  , surname: String
  , pending: [{
    seen: Boolean
    , contract_id: mongoose.Schema.ObjectId
    , signee_id: mongoose.Schema.ObjectId
  }]
});

let User = mongoose.model("Users", Schema);

let testObj = {
  "_id" : mongoose.Schema.ObjectId("5846ac7b11f83798104e1fce")
  , "name" : "Yves"
  , "surname" : "Rivard"
  , "pending" : [
    {
      "seen" : false
      , "contract_id" : mongoose.Schema.ObjectId("5a0ed25fbf3cd52f8413c4bf")
      , "signee_id" : mongoose.Schema.ObjectId("5a0ed268bf3cd52f8413c4c0")
    }
  ]
};


(async () => {
  try{
    let user = new User(testObj);

    await user.save();

    task.update('users', { _id: mongoose.Schema.ObjectId("5846ac7b11f83798104e1fce") }, {
      $pull: {
        pending: {
          contract_id: mongoose.Schema.ObjectId("5a0ed25fbf3cd52f8413c4bf")
        }
      }
    });

    let result = await task.run({useMongoose: true});

    console.log(result);
  }
  catch (err) {
    console.log(err);
  }
})();
```

**Comment by e-oj** [comment] 2017-11-17 21:32
@sakilo1990 Do you still have issues with this? Did you figure out what was going on?

**Comment by e-oj** [comment] 2017-11-17 23:35
@sakilo1990 I'll be closing this Issue. Feel free to reopen it if you have further questions.

**Comment by e-oj** [comment] 2017-11-19 15:58
Might be related to #34

**Comment by sakilo1990** [comment] 2017-11-20 07:18
Thanks for the fast responses! It seems that setting the flag { useMongoose: true } fixed the issue for me. Do you know what the reason could be?

**Comment by e-oj** [comment] 2017-11-20 19:52
Mongoose casts _id strings to ObjectId before queries and the native driver doesn't. I'm working on clearing up confusions about how ObjectId's are treated. Also, if you're using mongoose, you have to set the 'useMongoose' option

**Closed** 2017-11-20 19:53 UTC

**Comment by CriptoGirl** [comment] 2019-02-24 17:02
I had a number of similar issues with the update, but in the end, the following worked: 
try {
      await new Fawn.Task()
      .update('collection', 
                   { _id: mongoose.Types.ObjectId(req.params.id) } , 
                   { name: 'test', desc: 'description })
      .run({useMongoose: true});
} 
catch(err) { console.log(err); }
